# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githashcrash < Formula
  desc ""
  homepage "https://github.com/zegl/githashcrash/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.1/githashcrash_0.0.1_darwin_arm64.tar.gz"
      sha256 "3852b7fc9f2899ff5e44a996df05cd39d7dcf95779ed22f66c36d8c7db3a177e"

      def install
        bin.install "githashcrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.1/githashcrash_0.0.1_darwin_amd64.tar.gz"
      sha256 "9152d8686262f07e9af900516abf856ef47a93189673159be474926d36cd98e8"

      def install
        bin.install "githashcrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.1/githashcrash_0.0.1_linux_arm64.tar.gz"
      sha256 "b104c44a8b4fba25fc19bd9cefcc090689d0d3be8f4f28861c744f3957b8f2c0"

      def install
        bin.install "githashcrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.1/githashcrash_0.0.1_linux_amd64.tar.gz"
      sha256 "bfa41fad23aae631dd238d28b6464b88e5a4cb275fd0dd0c96ee246b65b85253"

      def install
        bin.install "githashcrash"
      end
    end
  end
end
