# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githashcrash < Formula
  desc ""
  homepage "https://github.com/zegl/githashcrash/"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.2/githashcrash_0.0.2_darwin_arm64.tar.gz"
      sha256 "55aadd43cf57b2bb9b0461072f4d60bb14c3a6854c11e1ea2b176accbcfd6714"

      def install
        bin.install "githashcrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.2/githashcrash_0.0.2_darwin_amd64.tar.gz"
      sha256 "e9f04265d0a85a5d2b870e0b2c56bde6a2a2724971235f064754bf83995a030c"

      def install
        bin.install "githashcrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.2/githashcrash_0.0.2_linux_arm64.tar.gz"
      sha256 "4af8ff4d30a2eadd836448e25f5b34b8d06148cb3a336ba9f8790472ff3a91d6"

      def install
        bin.install "githashcrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zegl/githashcrash/releases/download/v0.0.2/githashcrash_0.0.2_linux_amd64.tar.gz"
      sha256 "b4fe8581c6f46e084b659cf357bfa6cb4b7f9efa600135c6731a27450ca54905"

      def install
        bin.install "githashcrash"
      end
    end
  end
end
